name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3"
          cache: "poetry"

      - name: Install Dev dependencies
        run: poetry install

      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: success

      - name: Exit if CI did not succeed
        if: steps.wait-for-ci.outputs.conclusion != 'success'
        run: exit 1

      - name: Publish on PyPI
        run: scripts/publish
        env:
          PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"
